### ISSUE TITLE
Error building externals builder image for CentOS 7

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_development_environment#91]
```
$ DOCKER_BUILDKIT=1 docker build -f externals_builder.centos7.Dockerfile -t irods-externals-builder:centos-7 .
[+] Building 134.3s (12/13)                                                                                                                                                                  
 => [internal] load .dockerignore                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => [internal] load build definition from externals_builder.centos7.Dockerfile                                                                                                          0.1s
 => => transferring dockerfile: 1.76kB                                                                                                                                                  0.0s
 => resolve image config for docker.io/docker/dockerfile:1.5                                                                                                                            0.4s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io                                                                                                                        0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.5@sha256:39b85bbfa7536a5feceb7372a0817649ecb2724562a38360f4d6a7782a409b14                                                       0.0s
 => [internal] load metadata for docker.io/library/centos:7                                                                                                                             0.0s
 => [internal] load build context                                                                                                                                                       0.1s
 => => transferring context: 56B                                                                                                                                                        0.0s
 => [stage-0 1/7] FROM docker.io/library/centos:7                                                                                                                                       0.1s
 => [stage-0 2/7] RUN --mount=type=cache,target=/var/cache/yum,sharing=locked     yum update -y || [ "$?" -eq 100 ] &&     rm -rf /tmp/*                                               72.6s
 => [stage-0 3/7] RUN --mount=type=cache,target=/var/cache/yum,sharing=locked     yum install -y         centos-release-scl         epel-release     &&     yum install -y         su  55.9s
 => [stage-0 4/7] WORKDIR /externals                                                                                                                                                    0.5s 
 => ERROR [stage-0 5/7] RUN --mount=type=cache,target=/var/cache/yum,sharing=locked     git clone https://github.com/irods/externals -b "main" /externals &&     python3 -m venv build  4.2s 
------                                                                                                                                                                                       
 > [stage-0 5/7] RUN --mount=type=cache,target=/var/cache/yum,sharing=locked     git clone https://github.com/irods/externals -b "main" /externals &&     python3 -m venv build_env &&     source build_env/bin/activate &&     ./install_prerequisites.py &&     rm -rf /externals /tmp/*:                                                                                               
#0 0.692 Cloning into '/externals'...                                                                                                                                                        
#0 4.046 Traceback (most recent call last):                                                                                                                                                  
#0 4.046   File "./install_prerequisites.py", line 4, in <module>                                                                                                                            
#0 4.046     import build
#0 4.046   File "/externals/build.py", line 11, in <module>
#0 4.046     import distro
#0 4.046 ModuleNotFoundError: No module named 'distro'
------
externals_builder.centos7.Dockerfile:30
--------------------
  29 |     WORKDIR /externals
  30 | >>> RUN --mount=type=cache,target=/var/cache/yum,sharing=locked \
  31 | >>>     git clone https://github.com/irods/externals -b "${externals_branch}" /externals && \
  32 | >>>     python3 -m venv build_env && \
  33 | >>>     source build_env/bin/activate && \
  34 | >>>     ./install_prerequisites.py && \
  35 | >>>     rm -rf /externals /tmp/*
  36 |     
--------------------
ERROR: failed to solve: process "/usr/bin/bash -c git clone https://github.com/irods/externals -b \"${externals_branch}\" /externals &&     python3 -m venv build_env &&     source build_env/bin/activate &&     ./install_prerequisites.py &&     rm -rf /externals /tmp/*" did not complete successfully: exit code: 1
```

**Comment by korydraughn** [comment]
This also happened for Almalinux 8.

**Comment by SwooshyCueb** [comment]
Looks like the distro module needs to be installed in the python venv.
I'm not sure we need to be using a venv at all on almalinux 8 though.
I'll look into it.

**Comment by korydraughn** [comment]
Alma seems fine. CentOS 7 may need the venv since there doesn't appear to be a python3-distro package available to it.

I'm going to try building externals from scratch again for each of them to confirm.

**Comment by SwooshyCueb** [comment]
> CentOS 7 may need the venv since there doesn't appear to be a python3-distro package available to it.

`python3-distro` is provided by [`python36-distro`](https://rhel.pkgs.org/7/epel-x86_64/python36-distro-1.5.0-1.el7.noarch.rpm.html#required_by) from the EPEL repo.

**Comment by korydraughn** [comment]
After clearing my cache, the image builds just fine so I have to assume the python3-distro line resolves to python36-distro.

Thoughts?

**Comment by SwooshyCueb** [comment]
> After clearing my cache, the image builds just fine so I have to assume the python3-distro line resolves to python36-distro.
> 
> Thoughts?

I think `yum` might not be deterministic. See my comment on the PR: https://github.com/irods/irods_development_environment/pull/92#issuecomment-1688624531
